controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
    
oneup_uploader:
    resource: .
    type: uploader

dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
